#!/bin/bash

cd "$(dirname "$0")"

noFiles=1

if [[ ! -d "$HOME/bin"  ]] then
	echo "Folder  $HOME/bin don't exists, create it manually and add to PATH"
	exit 1;
fi

for FILE in *; do
    if [[ "$FILE" != "doLinks" && "$FILE" != "LICENSE" && "$FILE" != "README"* ]] then
       	noFiles=0
	ln -sf "$(realpath "$FILE")" "$HOME/bin/$FILE"
    fi
done

if [[ $noFiles = 1 ]] then
	echo "No Links to make, since there are no scripts"
	exit 1;
fi


echo "Links Created successfully"
exit 0;
